### ISSUE TITLE
Cria uma relação - M-N Doença e Idade 

### ISSUE THREAD

**Issue by matheuslins** [Projeto-BD/vacinou_project#1]
Até dia 03/02/15 às 5 da manhã com a issue resolvida

**Comment by uchoavaz** [comment]
Relação criada( O django cria uma tabela a mais por causa da relação m-n.A tabela se chama 'idade_id_vacina' e possui atributos id, id_vacina,id_idade, tendo todos como pk e id_vacina e id_idade com fk.

**Comment by matheuslins** [comment]
Showww, entendi !
