### ISSUE TITLE
Modificar a query do form e template de idades + consultas

### ISSUE THREAD

**Issue by matheuslins** [Projeto-BD/vacinou_project#2]
até dia 03/02/15 ás 16h com a issue resolvida

**Comment by uchoavaz** [comment]
Feito

**Comment by matheuslins** [comment]
Reabrindo para a implementação da nova relação entre vacina e doença, com isso essa issue ainda precisa modificar mais coisas, então, não feita ainda.

**Comment by uchoavaz** [comment]
feito
